using MeisterDev.ProPR.CodeInsights.Contracts;

// Copyright (c) Andreas Rain.
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license terms.


namespace MeisterDev.ProPR.CodeInsights.Tests.Contracts;

/// <summary>
///     The fallback that keeps ProPR's own words and the provider's own audit entries out of what it is said to
///     have missed, for the two cases identity cannot reach: a summary posted before provenance was recorded, and
///     a row already stored from an earlier harvest.
/// </summary>
public sealed class HarvestedThreadEligibilityTests
{
    [Fact]
    public void ProPrsOwnSummaryIsNotAThreadItFailedToRaise()
    {
        var discussion =
            "0caeb875-08d2-6d69-88fb-302b06d21993: **AI Review Summary**\n\n"
            + "This PR adds a review history experience to the admin UI.";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void ASummaryWithAHumanReplyUnderItIsStillNotAMiss()
    {
        // A person replying to ProPR's summary is talking to ProPR about a review it already gave. Whatever that
        // thread is, it is not something the reviewer failed to raise.
        var discussion =
            "0caeb875-08d2-6d69-88fb-302b06d21993: **AI Review Summary**\n"
            + "alice: thanks, fixed the paging one";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void AThreadOfNothingButProviderActivityIsNotAHumanThread()
    {
        var discussion = "00000002-0000-8888-8000-000000000000: Andreas Rain added Meister ProPR as a reviewer";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void AHumanThreadWithAnActivityEntryOnItStillCounts()
    {
        // The activity entry is not what a person said, and it is not a reason to discard what they did say.
        var discussion =
            "alice: this drops the retry count silently\n"
            + "00000002-0000-8888-8000-000000000000: Andreas Rain added Meister ProPR as a reviewer";

        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Theory]
    [InlineData("alice: this drops the retry count silently")]
    [InlineData("alice@example.com: the guard clause here is inverted")]
    // A comment that happens to talk about a summary is a person talking, not a summary.
    [InlineData("bob: the **AI Review Summary** above missed this file")]
    public void WhatAPersonWroteIsKept(string discussion)
    {
        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   \n  ")]
    public void NothingSaidIsNotAHumanThread(string? discussion)
    {
        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void ASummaryCarryingTheMarkerIsNotAThreadItFailedToRaise()
    {
        // GitHub, GitLab and Forgejo open a summary with the reviewer's display name, which differs per
        // installation. The marker is what identifies the summary as ProPR's on those hosts.
        var discussion =
            "0caeb875-08d2-6d69-88fb-302b06d21993: ## Meister Review Bot Review\n"
            + "This PR adds a review history experience to the admin UI.\n"
            + "*Generated by ProPR, an AI code reviewer.*";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void AConfiguredWordingIsRecognisedWhenItIsPassed()
    {
        var discussion =
            "0caeb875-08d2-6d69-88fb-302b06d21993: ## Meister Review Bot Review\n"
            + "This PR adds a review history experience to the admin UI.\n"
            + "*Erzeugt von ProPR.*";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion, "*Erzeugt von ProPR.*"));
        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void TheDefaultWordingIsRecognisedAfterTheWordingWasChanged()
    {
        // Comments posted before the installation configured a wording of its own carry the default one.
        var discussion =
            "0caeb875-08d2-6d69-88fb-302b06d21993: ## Meister Review Bot Review\n"
            + "This PR adds a review history experience to the admin UI.\n"
            + "*Generated by ProPR, an AI code reviewer.*";

        Assert.False(HarvestedThreadEligibility.IsHumanThread(discussion, "*Erzeugt von ProPR.*"));
    }

    [Fact]
    public void AQuoteOfAMarkedCommentIsStillWhatAPersonWrote()
    {
        var discussion =
            "alice: this drops the retry count silently\n"
            + "> *Generated by ProPR, an AI code reviewer.*";

        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Fact]
    public void APersonWritingAboutTheMarkerIsStillAPersonTalking()
    {
        var discussion = "bob: the *Generated by ProPR, an AI code reviewer.* line belongs at the top";

        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }

    [Theory]
    // ProPR emphasizes the marker with one asterisk on each side. A line under heavier emphasis came from
    // somebody typing it, and dropping it would take a real thread out of the recall measurement.
    [InlineData("alice: **Generated by ProPR, an AI code reviewer.**")]
    [InlineData("alice: ***Generated by ProPR, an AI code reviewer.***")]
    public void TheWordingUnderEmphasisProPrDoesNotEmitIsWhatAPersonWrote(string discussion)
    {
        Assert.True(HarvestedThreadEligibility.IsHumanThread(discussion));
    }
}
