<!-- Copyright (c) Andreas Rain. -->
<!-- Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license terms. -->

<template>
    <div class="protocol-master-detail summary-master-detail">
        <nav class="protocol-sidebar" aria-label="Comment Navigation">
            <div class="sidebar-search-container">
                <i class="fi fi-rr-search search-icon"></i>
                <input
                    v-model="vm.globalSearchQuery"
                    type="text"
                    class="sidebar-search-input"
                    placeholder="Filter paths..."
                />
            </div>
            <div v-for="item in vm.commentSidebarItems" :key="item.path" class="sidebar-tree-node">
                <button
                    v-if="item.type === 'folder'"
                    class="folder-header tree-folder-btn"
                    :class="{ 'active-folder': vm.selectedCommentPath === item.path || vm.selectedCommentPath?.startsWith(item.path + '/') }"
                    :style="{ paddingLeft: `${item.depth * 1.5}rem` }"
                    @click="vm.toggleFolder(`comments:${item.path}`); vm.selectedCommentPath = item.path"
                >
                    <i class="fi fi-rr-angle-small-down folder-chevron" :class="{ collapsed: item.isCollapsed }"></i>
                    <i class="fi" :class="item.isCollapsed ? 'fi-rr-folder' : 'fi-rr-folder-open'"></i>
                    <span class="folder-name">{{ item.name }}</span>
                </button>

                <button
                    v-else
                    class="pass-nav-item tree-pass-btn comment-node-btn"
                    :class="{ active: vm.selectedCommentPath === item.path }"
                    :style="{ paddingLeft: `${item.depth * 1.5}rem` }"
                    @click="vm.selectedCommentPath = item.path"
                >
                    <i class="fi fi-rr-file-code file-icon"></i>
                    <div class="pass-nav-info">
                        <span class="pass-nav-filename">{{ item.name }}</span>
                        <span class="comment-count-pill">{{ item.commentCount }}</span>
                    </div>
                </button>
            </div>
        </nav>

        <div class="protocol-content">
            <div class="synthesis-main">
                <div class="ai-disclaimer summary-ai-disclaimer">
                    <i class="fi fi-rr-magic-wand ai-icon"></i>
                    <span class="ai-text">This review was generated by an AI assistant. It may contain inaccuracies or hallucinations.</span>
                </div>

                <div v-if="!vm.selectedCommentPath" class="summary-dashboard">
                    <div class="summary-dashboard-header">
                        <div class="title-group">
                            <h3>Review Summary</h3>
                            <p class="subtitle">Aggregated findings and executive summary</p>
                        </div>
                        <button class="ui-button primary-action" @click="vm.isSummaryModalOpen = true">
                            <i class="fi fi-rr-expand"></i>
                            View Full Summary & Findings
                        </button>
                    </div>

                    <div class="summary-preview-card">
                        <div class="overview-metadata-grid">
                            <div class="overview-metadata-item">
                                <span class="overview-metadata-label">Model</span>
                                <span class="overview-metadata-value monospace-value">{{ vm.reviewModelDisplay }}</span>
                            </div>
                            <div class="overview-metadata-item">
                                <span class="overview-metadata-label">Strategy</span>
                                <span class="overview-metadata-value">{{ vm.reviewStrategyDisplay }}</span>
                            </div>
                            <div class="overview-metadata-item">
                                <span class="overview-metadata-label">Temperature</span>
                                <span class="overview-metadata-value">{{ vm.reviewTemperatureDisplay }}</span>
                            </div>
                        </div>

                        <div
                            v-if="vm.reviewStatus?.result?.summary"
                            class="markdown-content preview-markdown"
                            v-html="vm.renderMarkdown(vm.reviewStatus.result.summary.substring(0, 500) + '...')"
                        ></div>
                        <div v-else-if="vm.reviewStatus?.status === 'processing'" class="synthesis-waiting-state">
                            <ProgressOrb class="waiting-orb" />
                            <p>Synthesizing Review...</p>
                        </div>
                        <div v-else class="empty-state">No summary available yet.</div>

                        <div class="dashboard-stats">
                            <div class="dash-stat">
                                <span class="dash-stat-value">{{ vm.commentSidebarItems.filter(i => i.type === 'file').length }}</span>
                                <span class="dash-stat-label">Files with findings</span>
                            </div>
                            <div class="dash-stat">
                                <span class="dash-stat-value">{{ vm.reviewStatus?.result?.comments?.length ?? 0 }}</span>
                                <span class="dash-stat-label">Total Comments</span>
                            </div>
                        </div>

                        <p
                            v-if="(vm.reviewStatus?.result?.comments?.length ?? 0) === 0 && vm.reviewStatus?.status !== 'processing'"
                            class="aggregate-clean-state"
                            data-testid="aggregate-clean-state"
                        >
                            No findings — the review completed clean.
                        </p>
                        <div v-else class="severity-summary-row">
                            <div
                                v-for="(count, sev) in vm.severityCounts"
                                :key="sev"
                                class="sev-summary-pill"
                                :class="`sev-summary-pill--${sev}`"
                                v-show="count > 0"
                            >
                                <span class="sev-summary-count">{{ count }}</span>
                                <span class="sev-summary-label">{{ sev }}</span>
                            </div>
                        </div>
                    </div>

                    <!-- Aggregate findings view: every finding, grouped by file, each
                         annotated with the pass that produced it (origin badge). This is
                         the provenance home per EXPERIENCE.md §IA. -->
                    <section
                        v-if="(vm.reviewStatus?.result?.comments?.length ?? 0) > 0"
                        class="aggregate-findings-section"
                        data-testid="aggregate-findings"
                    >
                        <div class="aggregate-findings-header">
                            <h4>Findings by file</h4>
                            <span class="aggregate-findings-hint">Each finding links to the pass that produced it.</span>
                        </div>
                        <JobProtocolCommentGroups
                            :vm="vm"
                            :groups="vm.aggregateFindingsByFile"
                            empty-message="No findings — the review completed clean."
                            show-origin
                            show-root-header
                        />
                    </section>
                </div>

                <section v-else class="events-section selected-file-view">
                    <div class="comments-section has-selection">
                        <div class="comments-toolbar">
                            <div class="back-to-summary-row">
                                <button class="btn-ghost back-to-summary-btn" @click="vm.selectedCommentPath = null">
                                    ← Back to Summary
                                </button>
                            </div>
                            <h4 class="comments-main-title">Comments for {{ vm.selectedCommentPath }}</h4>
                            <div class="comments-filter-controls">
                                <input v-model="vm.localSearchQuery" type="text" class="comment-search-input" placeholder="Search file comments…" />
                                <div class="severity-pills">
                                    <button
                                        v-for="sev in severities"
                                        :key="sev"
                                        class="severity-pill"
                                        :class="[`severity-pill--${sev}`, { 'severity-pill--active': vm.localSeverities.has(sev) }]"
                                        :data-severity="sev"
                                        @click="vm.toggleSeverity(sev)"
                                    >
                                        {{ sev }}
                                    </button>
                                </div>
                            </div>
                        </div>

                        <JobProtocolCommentGroups
                            :vm="vm"
                            :groups="vm.groupedReviewComments"
                            empty-message="No comments found for this selection."
                            show-dismiss
                            show-origin
                        />
                    </div>
                </section>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import ProgressOrb from '@/components/ProgressOrb.vue'
import type { JobProtocolViewModel } from '@/features/job-protocol/composables/useJobProtocolViewModel'
import JobProtocolCommentGroups from './JobProtocolCommentGroups.vue'

defineProps<{ vm: JobProtocolViewModel }>()

const severities = ['error', 'warning', 'info', 'suggestion']
</script>

<style scoped>
.protocol-master-detail {
    display: grid;
    grid-template-columns: 320px 1fr;
    gap: 2rem;
    align-items: start;
}

@media (max-width: 1024px) {
    .protocol-master-detail {
        grid-template-columns: 1fr;
        gap: 1rem;
    }
}

.protocol-sidebar {
    width: 100%;
    max-width: 320px;
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    height: fit-content;
    position: sticky;
    top: 1rem;
    padding: 0 1rem;
    z-index: 10;
    max-height: calc(100vh - 4rem);
    overflow-y: auto;
}

@media (max-width: 1024px) {
    .protocol-sidebar {
        max-width: none;
        position: static;
        top: auto;
        max-height: none;
        padding: 0;
    }
}

.sidebar-search-container {
    padding: 0.5rem;
    position: sticky;
    top: 0;
    background: var(--color-bg);
    z-index: 10;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    border-bottom: 1px solid var(--color-border);
    margin-bottom: 0.5rem;
}

.sidebar-search-input {
    background: transparent;
    border: none;
    color: var(--color-text);
    font-size: 0.85rem;
    width: 100%;
    outline: none;
}

.search-icon {
    font-size: 0.8rem;
    opacity: 0.5;
}

.sidebar-tree-node {
    position: relative;
    display: flex;
    flex-direction: column;
    width: 100%;
}

.folder-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 0.25rem;
    background: transparent !important;
    border: none;
    color: var(--color-text-muted);
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    cursor: pointer;
    width: 100%;
    border-radius: 0 !important;
}

.tree-folder-btn {
    appearance: none;
    background: transparent !important;
    border: none;
    display: flex;
    align-items: center;
    justify-content: flex-start !important;
    text-align: left !important;
    gap: 0.2rem;
    padding: 0.25rem 0.5rem;
    color: var(--color-accent);
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: none;
    cursor: pointer;
    width: 100%;
    transition: all 0.1s ease;
    border-radius: var(--radius-xs);
    z-index: 2;
    margin: 1px 0;
}

.tree-folder-btn:hover {
    background: rgba(255, 255, 255, 0.06) !important;
}

.folder-chevron {
    font-size: 0.6rem;
    transition: transform 0.15s ease;
    opacity: 0.6;
    width: 0.8rem;
    display: inline-flex;
    justify-content: center;
    margin-right: 0.2rem;
}

.folder-chevron.collapsed {
    transform: rotate(-90deg);
}

.folder-name {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.tree-pass-btn {
    appearance: none;
    background: transparent !important;
    border: none !important;
    box-shadow: none !important;
    display: flex;
    align-items: center;
    justify-content: flex-start !important;
    text-align: left !important;
    gap: 0.6rem;
    padding: 0.2rem 0.5rem;
    cursor: pointer;
    width: 100%;
    border-radius: var(--radius-xs);
    transition: all 0.1s ease;
    margin: 1px 0;
    z-index: 2;
    min-height: auto !important;
}

.tree-pass-btn:hover {
    background: rgba(255, 255, 255, 0.04) !important;
}

.tree-pass-btn.active {
    background: rgba(59, 130, 246, 0.12) !important;
}

.comment-node-btn .pass-nav-info {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    width: 100%;
}

.pass-nav-info {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: 0.5rem;
    flex: 1;
    min-width: 0;
}

.pass-nav-filename {
    font-size: 0.8rem;
    font-weight: 500;
}

.comment-count-pill {
    font-size: 0.7rem;
    background: rgba(255, 255, 255, 0.15);
    color: var(--color-text);
    padding: 0.13rem 0.45rem;
    border-radius: var(--radius-lg);
    font-weight: 700;
}

.active .comment-count-pill {
    background: rgba(255, 255, 255, 0.25);
    color: var(--color-accent) !important;
}

.active-folder {
    background: rgba(255, 255, 255, 0.03) !important;
}

.file-icon {
    color: var(--color-text-muted) !important;
    opacity: 0.9;
}

.protocol-content {
    background: var(--color-surface);
    border-radius: var(--radius-lg);
    padding: 0;
    border: 1px solid var(--color-border);
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

.synthesis-main {
    width: 100%;
}

.summary-ai-disclaimer {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    background: rgba(139, 92, 246, 0.1);
    border: 1px solid rgba(139, 92, 246, 0.3);
    padding: 1rem 1.25rem;
    border-radius: var(--radius-md);
    margin: 1.5rem 2rem;
}

.ai-icon {
    font-size: 1.25rem;
}

.ai-text {
    font-size: 0.9rem;
    color: var(--color-text);
    font-weight: 500;
}

.summary-dashboard {
    padding: 2rem;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}

.summary-dashboard-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    border-bottom: 1px solid var(--color-border);
    padding-bottom: 1rem;
}

.summary-dashboard-header h3 {
    margin: 0;
    font-size: 1.5rem;
}

.subtitle {
    margin: 0.25rem 0 0;
    color: var(--color-text-muted);
    font-size: 0.9rem;
}

.summary-preview-card {
    background: rgba(255, 255, 255, 0.03);
    border-radius: var(--radius-xl);
    padding: 2rem;
    border: 1px solid var(--color-border);
}

.overview-metadata-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
    gap: 0.875rem;
    margin-bottom: 1.5rem;
}

.overview-metadata-item {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    padding: 0.9rem 1rem;
    border-radius: 0.875rem;
    background: rgba(255, 255, 255, 0.025);
    border: 1px solid var(--color-border);
}

.overview-metadata-label {
    font-size: 0.75rem;
    line-height: 1.1;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--color-text-muted);
}

.overview-metadata-value {
    font-size: 1rem;
    font-weight: 600;
    color: var(--color-text);
}

.preview-markdown {
    opacity: 0.85;
    mask-image: linear-gradient(to bottom, black 70%, transparent 100%);
    max-height: 200px;
    overflow: hidden;
}

.dashboard-stats {
    display: flex;
    gap: 3rem;
    margin-top: 2rem;
    padding-top: 2rem;
    border-top: 1px solid var(--color-border);
}

.dash-stat {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
}

.dash-stat-value {
    font-size: 2rem;
    font-weight: 700;
    color: var(--color-accent);
}

.dash-stat-label {
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted);
}

.severity-summary-row {
    display: flex;
    gap: 0.75rem;
    margin-top: 1.5rem;
    flex-wrap: wrap;
}

.aggregate-clean-state {
    margin: 1.5rem 0 0;
    color: var(--color-text-muted);
    font-size: 0.9rem;
}

.aggregate-findings-section {
    margin-top: 1.5rem;
}

.aggregate-findings-header {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 0.5rem;
    border-bottom: 1px solid var(--color-border);
    padding-bottom: 0.5rem;
    margin-bottom: 0.5rem;
}

.aggregate-findings-header h4 {
    margin: 0;
    font-size: 0.95rem;
}

.aggregate-findings-hint {
    color: var(--color-text-muted);
    font-size: 0.78rem;
}

.sev-summary-pill {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.35rem 0.85rem;
    border-radius: var(--radius-md);
    font-size: 0.85rem;
    font-weight: 600;
    text-transform: capitalize;
    border: 1px solid var(--color-border);
}

.sev-summary-count {
    font-size: 1rem;
    font-family: monospace;
}

.sev-summary-pill--error { background: rgba(239, 68, 68, 0.1); border-color: rgba(239, 68, 68, 0.3); color: var(--color-danger); }
.sev-summary-pill--warning { background: rgba(234, 179, 8, 0.1); border-color: rgba(234, 179, 8, 0.3); color: var(--color-warning); }
.sev-summary-pill--info { background: rgba(59, 130, 246, 0.1); border-color: rgba(59, 130, 246, 0.3); color: var(--color-info); }
.sev-summary-pill--suggestion { background: rgba(168, 85, 247, 0.1); border-color: rgba(168, 85, 247, 0.3); color: var(--color-suggestion); }

.events-section,
.comments-section {
    padding: 1.5rem;
    flex: 1;
    overflow-y: auto;
    max-width: 1000px;
    margin: 0 auto;
    width: 100%;
}

.comments-main-title {
    margin-top: 0 !important;
    text-align: left;
}

.comments-toolbar {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 0.75rem;
    margin-top: 1rem;
    margin-bottom: 1rem;
}

.comments-filter-controls {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
}

.comment-search-input {
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    padding: 0.35rem 0.75rem;
    color: var(--color-text);
    font-size: 0.85rem;
    width: 200px;
}

.comment-search-input:focus {
    outline: none;
    border-color: var(--color-accent);
    background: rgba(255, 255, 255, 0.08);
}

.severity-pills {
    display: flex;
    gap: 0.35rem;
    flex-wrap: wrap;
}

.severity-pill {
    padding: 0.35rem 0.85rem;
    border-radius: var(--radius-md);
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
    text-transform: capitalize;
    border: 1px solid var(--color-border);
    background: rgba(255, 255, 255, 0.05);
    color: var(--color-text-muted);
    transition: all 0.15s ease;
    display: flex;
    align-items: center;
    justify-content: center;
}

.severity-pill:hover {
    background: rgba(255, 255, 255, 0.1);
    color: var(--color-text);
    border-color: rgba(255, 255, 255, 0.2);
}

.severity-pill--error.severity-pill--active { background: rgba(239, 68, 68, 0.15); border-color: rgba(239, 68, 68, 0.4); color: var(--color-danger); }
.severity-pill--warning.severity-pill--active { background: rgba(234, 179, 8, 0.15); border-color: rgba(234, 179, 8, 0.4); color: var(--color-warning); }
.severity-pill--info.severity-pill--active { background: rgba(59, 130, 246, 0.15); border-color: rgba(59, 130, 246, 0.4); color: var(--color-info); }
.severity-pill--suggestion.severity-pill--active { background: rgba(168, 85, 247, 0.15); border-color: rgba(168, 85, 247, 0.4); color: var(--color-suggestion); }

.synthesis-waiting-state {
    padding: 4rem 2rem;
    display: flex;
    justify-content: center;
    border: 1px dashed var(--color-border);
    border-radius: var(--radius-lg);
    background: rgba(255, 255, 255, 0.02);
}

.waiting-orb {
    width: 48px;
    height: 48px;
    margin: 0 auto 1.5rem;
}

.markdown-content :deep(h1),
.markdown-content :deep(h2),
.markdown-content :deep(h3),
.markdown-content :deep(h4) {
    font-size: 1.1rem;
    margin: 1.25rem 0 0.5rem;
    color: var(--color-text);
    font-weight: 600;
}

.markdown-content :deep(p) {
    margin-bottom: 0.75rem;
    line-height: 1.6;
}

.back-to-summary-row {
    margin-bottom: 0.5rem;
}

.back-to-summary-btn {
    font-size: 0.85rem;
    padding: 0.25rem 0.5rem;
}
</style>
