// Copyright (c) Andreas Rain.
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license terms.

using System.ComponentModel.DataAnnotations;
using MeisterDev.ProPR.Application.Options;
using MeisterDev.ProPR.Application.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace MeisterDev.ProPR.Application.Tests.Options;

/// <summary>
///     Verifies which marker wordings an installation may configure. A value a host would not render as
///     written has to be refused at startup, not silently altered on its way to a pull request.
/// </summary>
public sealed class PostedCommentMarkerOptionsTests
{
    [Fact]
    public void UnsetMarker_PassesValidation()
    {
        Assert.True(TryValidate(new PostedCommentMarkerOptions(), out _));
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void BlankMarker_PassesValidation(string marker)
    {
        Assert.True(TryValidate(new PostedCommentMarkerOptions { Marker = marker }, out _));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void BlankMarkerFromInMemoryConfiguration_StartsUpOnTheDefaultWording(string? configuredValue)
    {
        var configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(
                new Dictionary<string, string?>
                {
                    ["MEISTER_AI_GENERATED_MARKER"] = configuredValue,
                })
            .Build();

        var services = new ServiceCollection();
        services.AddOptions<PostedCommentMarkerOptions>()
            .Configure(options => options.Marker = configuration["MEISTER_AI_GENERATED_MARKER"])
            .ValidateDataAnnotations()
            .ValidateOnStart();

        using var provider = services.BuildServiceProvider();

        provider.GetRequiredService<IStartupValidator>().Validate();

        var composer = new PostedCommentComposer(provider.GetRequiredService<IOptions<PostedCommentMarkerOptions>>());
        Assert.Equal("*" + PostedCommentMarkerOptions.DefaultMarker + "*", composer.Text);
    }

    [Fact]
    public void PlainWording_PassesValidation()
    {
        var options = new PostedCommentMarkerOptions { Marker = "Von ProPR erzeugt, einem KI-Reviewer." };

        Assert.True(TryValidate(options, out _));
    }

    [Theory]
    [InlineData("Generated by <b>ProPR</b>")]
    [InlineData("Generated by ProPR > a reviewer")]
    [InlineData("Generated by ProPR & reviewed by nobody")]
    [InlineData("Generated by \"ProPR\"")]
    [InlineData("Generated by ProPR\nan AI code reviewer")]
    [InlineData("/generated by ProPR")]
    public void MarkerOutsideTheAcceptedCharacters_FailsValidationNamingTheVariable(string marker)
    {
        var options = new PostedCommentMarkerOptions { Marker = marker };

        Assert.False(TryValidate(options, out var results));
        Assert.Contains(
            results, result => result.ErrorMessage?.Contains(
                "MEISTER_AI_GENERATED_MARKER",
                StringComparison.Ordinal) == true);
    }

    [Theory]
    [InlineData("Generated by *ProPR*")]
    [InlineData("Generated by _ProPR_")]
    [InlineData("Generated by `ProPR`")]
    [InlineData("Generated by [ProPR](https://example.com)")]
    [InlineData("Generated by ProPR \\ an AI code reviewer")]
    [InlineData("# Generated by ProPR")]
    public void MarkerCarryingMarkdownSyntax_FailsValidation(string marker)
    {
        var options = new PostedCommentMarkerOptions { Marker = marker };

        Assert.False(TryValidate(options, out _));
    }

    [Fact]
    public void MarkerEndingInALineBreak_FailsValidation()
    {
        var options = new PostedCommentMarkerOptions { Marker = "Generated by ProPR, an AI code reviewer.\n" };

        Assert.False(TryValidate(options, out _));
    }

    // A break of any kind splits the marker away from the comment it belongs to, and the invisible characters
    // beside them let a wording render as something other than what is stored: a bidirectional override
    // reverses the text a reviewer reads, and a zero-width joiner leaves a marker nobody can see.
    [Theory]
    [InlineData("Generated by ProPR\rand nothing else")] // carriage return
    [InlineData("Generated by ProPR\u000bby an AI")] // vertical tab
    [InlineData("Generated by ProPR\u0085by an AI")] // next line
    [InlineData("Generated by ProPR\u0000by an AI")] // null
    [InlineData("Generated by ProPR\u200dby an AI")] // zero-width joiner
    [InlineData("Generated by ProPR\u202eby an AI")] // right-to-left override
    [InlineData("Generated by ProPR\u2028by an AI")] // line separator
    [InlineData("Generated by ProPR\u2029by an AI")] // paragraph separator
    public void MarkerCarryingAControlFormattingOrSeparatorCharacter_FailsValidation(string marker)
    {
        var options = new PostedCommentMarkerOptions { Marker = marker };

        Assert.False(TryValidate(options, out _));
    }

    // The rejected set is the invisible and the breaking characters, so an ordinary space and the punctuation
    // of a language the wording is written in stay accepted.
    [Theory]
    [InlineData("Généré par ProPR, un relecteur IA.")]
    [InlineData("由 ProPR 生成，一个 AI 代码审查员。")]
    [InlineData("Создано ProPR - ИИ-рецензентом.")]
    public void MarkerInAnotherScript_PassesValidation(string marker)
    {
        var options = new PostedCommentMarkerOptions { Marker = marker };

        Assert.True(TryValidate(options, out _));
    }

    [Fact]
    public void TheDefaultWording_PassesValidation()
    {
        var options = new PostedCommentMarkerOptions { Marker = PostedCommentMarkerOptions.DefaultMarker };

        Assert.True(TryValidate(options, out _));
    }

    [Fact]
    public void MarkerLongerThanTheBound_FailsValidation()
    {
        var options = new PostedCommentMarkerOptions { Marker = new string('x', 201) };

        Assert.False(TryValidate(options, out _));
    }

    [Fact]
    public void MarkerAtTheBound_PassesValidation()
    {
        var options = new PostedCommentMarkerOptions { Marker = new string('x', 200) };

        Assert.True(TryValidate(options, out _));
    }

    private static bool TryValidate(PostedCommentMarkerOptions options, out List<ValidationResult> results)
    {
        results = [];
        return Validator.TryValidateObject(
            options,
            new ValidationContext(options),
            results,
            validateAllProperties: true);
    }
}
