// Copyright (c) Andreas Rain.
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license terms.

// This file implements commercial-only functionality. A commercial license is required to activate or use that functionality.

namespace MeisterDev.ProPR.CodeInsights.Contracts;

/// <summary>Decodes providerless stored discussion evidence without inferring current native capabilities.</summary>
public static class HistoricalPublicationEvidenceDecoder
{
    public const string SummaryPrefix = "**AI Review Summary**";
    public const string DefaultMarkerWording = "Generated by ProPR, an AI code reviewer.";
    private const string ServiceActivityAuthor = "00000002-0000-8888-8000-000000000000";

    public static HistoricalPublicationEvidence DecodeLine(string line, string? generatedMarker = null)
    {
        var separator = line.IndexOf(':', StringComparison.Ordinal);
        var author = separator < 0 ? string.Empty : line[..separator].Trim();
        var text = separator < 0 ? line : line[(separator + 1)..].Trim();
        return new(
            text.StartsWith(SummaryPrefix, StringComparison.Ordinal)
            || IsMarkerLine(line, generatedMarker) || IsMarkerLine(text, generatedMarker),
            string.Equals(author, ServiceActivityAuthor, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsMarkerLine(string candidate, string? generatedMarker)
    {
        var wording = Unemphasize(candidate);
        if (wording.Length == 0)
        {
            return false;
        }

        return string.Equals(wording, DefaultMarkerWording, StringComparison.Ordinal)
               || (generatedMarker is not null
                   && string.Equals(wording, Unemphasize(generatedMarker), StringComparison.Ordinal));
    }

    /// <summary>
    ///     Accepts bare marker wording or wording wrapped in one asterisk on each side.
    /// </summary>
    /// <remarks>
    ///     Longer asterisk runs remain unchanged so quoted or bold marker wording does not exclude a human thread.
    /// </remarks>
    private static string Unemphasize(string value)
    {
        var trimmed = value.Trim();
        if (trimmed.Length < 2 || trimmed[0] != '*' || trimmed[^1] != '*')
        {
            return trimmed;
        }

        var inner = trimmed[1..^1];
        return inner.StartsWith('*') || inner.EndsWith('*') ? trimmed : inner.Trim();
    }
}

/// <summary>Stored evidence of an own publication or a provider activity line.</summary>
public sealed record HistoricalPublicationEvidence(bool IsOwnPublication, bool IsProviderActivity);
