// <auto-generated />
using System;
using MeisterProPR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeisterProPR.Infrastructure.Migrations
{
    [DbContext(typeof(MeisterProPRDbContext))]
    [Migration("20260327100000_AddExcludedToFileResults")]
    partial class AddExcludedToFileResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionPrScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CrawlConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_configuration_id");

                    b.Property<DateTimeOffset>("LastCommentSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_comment_seen_at");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CrawlConfigurationId", "RepositoryId", "PullRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_pr_scans_pr");

                    b.ToTable("mention_pr_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionProjectScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CrawlConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_configuration_id");

                    b.Property<DateTimeOffset>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CrawlConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_project_scans_config");

                    b.ToTable("mention_project_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionReplyJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("MentionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mention_text");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_mention_reply_jobs_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mention_reply_jobs_status");

                    b.HasIndex("ClientId", "PullRequestId", "ThreadId", "CommentId")
                        .IsUnique()
                        .HasDatabaseName("uq_mention_reply_jobs_mention");

                    b.ToTable("mention_reply_jobs", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ProtocolEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("InputTextSample")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("input_text_sample");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OutputSummary")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("output_summary");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid")
                        .HasColumnName("protocol_id");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId")
                        .HasDatabaseName("ix_protocol_events_protocol_id");

                    b.ToTable("protocol_events", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewFileResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasColumnType("jsonb")
                        .HasColumnName("comments_json");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExclusionReason")
                        .HasColumnType("text")
                        .HasColumnName("exclusion_reason");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_excluded");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_failed");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PerFileSummary")
                        .HasColumnType("text")
                        .HasColumnName("per_file_summary");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_review_file_results_job_id");

                    b.HasIndex("JobId", "FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_review_file_results_job_file");

                    b.ToTable("review_file_results", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("IterationId")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_id");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long?>("TotalInputTokensAggregated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens_aggregated");

                    b.Property<long?>("TotalOutputTokensAggregated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens_aggregated");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_review_jobs_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_review_jobs_status");

                    b.HasIndex("OrganizationUrl", "ProjectId", "RepositoryId", "PullRequestId", "IterationId")
                        .HasDatabaseName("ix_review_jobs_pr_identity");

                    b.ToTable("review_jobs", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJobProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("FileResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_result_id");

                    b.Property<int?>("FinalConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("final_confidence");

                    b.Property<int?>("IterationCount")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_count");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Label")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("label");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("ToolCallCount")
                        .HasColumnType("integer")
                        .HasColumnName("tool_call_count");

                    b.Property<long?>("TotalInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens");

                    b.Property<long?>("TotalOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens");

                    b.HasKey("Id");

                    b.HasIndex("FileResultId")
                        .HasDatabaseName("ix_review_job_protocols_file_result_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_review_job_protocols_job_id");

                    b.ToTable("review_job_protocols", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("LastProcessedCommitId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_processed_commit_id");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "RepositoryId", "PullRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_review_pr_scans_pr");

                    b.ToTable("review_pr_scans", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScanThread", b =>
                {
                    b.Property<Guid>("ReviewPrScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_pr_scan_id");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<int>("LastSeenReplyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_seen_reply_count");

                    b.HasKey("ReviewPrScanId", "ThreadId");

                    b.ToTable("review_pr_scan_threads", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.AppUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GlobalRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("global_role");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_username");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.ClientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdoClientId")
                        .HasColumnType("text")
                        .HasColumnName("ado_client_id");

                    b.Property<string>("AdoClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("ado_client_secret");

                    b.Property<string>("AdoTenantId")
                        .HasColumnType("text")
                        .HasColumnName("ado_tenant_id");

                    b.Property<int>("AllowedScopes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7)
                        .HasColumnName("allowed_scopes");

                    b.Property<int>("CommentResolutionBehavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("comment_resolution_behavior");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomSystemMessage")
                        .HasColumnType("text")
                        .HasColumnName("custom_system_message");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("KeyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_expires_at");

                    b.Property<string>("KeyHash")
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("KeyRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_rotated_at");

                    b.Property<DateTimeOffset?>("PreviousKeyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_key_expires_at");

                    b.Property<string>("PreviousKeyHash")
                        .HasColumnType("text")
                        .HasColumnName("previous_key_hash");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_key");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("CrawlIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("crawl_interval_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_url");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_crawl_configurations_client_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_crawl_configurations_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("ClientId", "OrganizationUrl", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_crawl_configurations_unique_config");

                    b.ToTable("crawl_configurations", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.UserClientRoleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_client_roles_user_client");

                    b.ToTable("user_client_roles", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.UserPatRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_user_pats_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("user_pats", (string)null);
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionPrScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("CrawlConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionProjectScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("CrawlConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.MentionReplyJob", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ProtocolEvent", b =>
                {
                    b.HasOne("MeisterProPR.Domain.Entities.ReviewJobProtocol", null)
                        .WithMany("Events")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewFileResult", b =>
                {
                    b.HasOne("MeisterProPR.Domain.Entities.ReviewJob", null)
                        .WithMany("FileReviewResults")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJobProtocol", b =>
                {
                    b.HasOne("MeisterProPR.Domain.Entities.ReviewFileResult", null)
                        .WithMany()
                        .HasForeignKey("FileResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MeisterProPR.Domain.Entities.ReviewJob", null)
                        .WithMany("Protocols")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScanThread", b =>
                {
                    b.HasOne("MeisterProPR.Domain.Entities.ReviewPrScan", "ReviewPrScan")
                        .WithMany("Threads")
                        .HasForeignKey("ReviewPrScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewPrScan");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.CrawlConfigurationRecord", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.ClientRecord", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.RefreshTokenRecord", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.AppUserRecord", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.UserClientRoleRecord", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.AppUserRecord", "User")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.UserPatRecord", b =>
                {
                    b.HasOne("MeisterProPR.Infrastructure.Data.Models.AppUserRecord", "User")
                        .WithMany("Pats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJob", b =>
                {
                    b.Navigation("FileReviewResults");

                    b.Navigation("Protocols");
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewJobProtocol", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MeisterProPR.Domain.Entities.ReviewPrScan", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("MeisterProPR.Infrastructure.Data.Models.AppUserRecord", b =>
                {
                    b.Navigation("ClientAssignments");

                    b.Navigation("Pats");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
