#!/usr/bin/env -S dotnet --

using System.Text;

var appFilePath = GetAppFilePath();
var repoRoot = FindRepoRoot(Path.GetDirectoryName(appFilePath)!);
var outputFile = Path.Combine(repoRoot, "docs", "reference", "source-license-map.md");

const string commercialNotice = "This file implements commercial-only functionality. A commercial license is required to activate or use that functionality.";
const string licenseKeyNotice = "This file implements license key functionality. License logic may not be moved, changed, disabled or circumvented.";

var scanRoots = new[]
{
    Path.Combine(repoRoot, "src"),
    Path.Combine(repoRoot, "frontend", "src"),
};

var allowedExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    ".cs",
    ".ts",
    ".vue",
};

var markedFiles = scanRoots
    .Where(Directory.Exists)
    .SelectMany(root => Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
    .Where(path => allowedExtensions.Contains(Path.GetExtension(path)))
    .Select(path => new
    {
        Path = Path.GetRelativePath(repoRoot, path).Replace(Path.DirectorySeparatorChar, '/'),
        Text = File.ReadAllText(path),
    })
    .Select(file => new
    {
        file.Path,
        IsCommercial = file.Text.Contains(commercialNotice, StringComparison.Ordinal),
        IsLicenseKey = file.Text.Contains(licenseKeyNotice, StringComparison.Ordinal),
    })
    .Where(file => file.IsCommercial || file.IsLicenseKey)
    .OrderBy(file => file.Path, StringComparer.Ordinal)
    .ToArray();

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

var builder = new StringBuilder();
builder.AppendLine("# Source License Map");
builder.AppendLine();
builder.AppendLine("This file is generated by `scripts/update-source-license-map.cs`.");
builder.AppendLine("Do not edit it manually.");
builder.AppendLine();
builder.AppendLine("| Path or file | Source license | Capability classification | Notes |");
builder.AppendLine("|---|---|---|---|");
builder.AppendLine("| `docs/` | Elastic License 2.0 unless otherwise noted | Documentation | This row is maintained by the generator as a repository convention. |");

foreach (var file in markedFiles)
{
    var classification = file switch
    {
        { IsCommercial: true, IsLicenseKey: true } => "Commercial capability implementation and license key functionality",
        { IsLicenseKey: true } => "License key functionality",
        _ => "Commercial capability implementation",
    };

    var notes = file switch
    {
        { IsCommercial: true, IsLicenseKey: true } =>
            "Marked in-source with both notices. The Elastic License 2.0 restriction on circumventing license key functionality applies to it.",
        { IsLicenseKey: true } =>
            "Marked in-source with the license key functionality notice. It runs in every edition; the Elastic License 2.0 restriction on circumventing license key functionality applies to it.",
        _ => "Marked in-source with the commercial-only functionality notice.",
    };

    if (file.Path is "src/MeisterDev.ProPR.Api/Features/IdentityAndAccess/Controllers/TenantAuthController.cs"
        or "src/MeisterDev.ProPR.Infrastructure/Features/IdentityAndAccess/Persistence/TenantAuthService.cs")
    {
        classification = "Mixed file with commercial capability implementation";
        notes = "Marked in-source and contains shared behavior alongside commercial-only functionality.";
    }

    builder.Append("| `")
        .Append(file.Path)
        .Append("` | Elastic License 2.0 | ")
        .Append(classification)
        .Append(" | ")
        .Append(notes)
        .AppendLine(" |");
}

builder.AppendLine("| All other repository files unless otherwise noted | Elastic License 2.0 | Community or shared | Neither the commercial-only functionality notice nor the license key functionality notice was detected in the scanned source files. |");

File.WriteAllText(outputFile, builder.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Updated {outputFile}");

// The provider stack ships separately from the product, at the organisation level, so no file in it carries a
// commercial or license-key notice. The shipped families are also the reference implementations someone reads
// when writing a new one, and a family under a commercial notice is one nobody outside the team can learn from.
// Reported here because this sweep already reads every marked file; the project-graph half of the rule is a
// build check in Directory.Build.targets.
var providerStackPrefix = "src/MeisterDev.Ai.Providers";
var notPublishable = markedFiles
    .Where(file => file.Path.StartsWith(providerStackPrefix, StringComparison.Ordinal))
    .ToArray();

if (notPublishable.Length > 0)
{
    Console.Error.WriteLine(
        "The provider stack must carry no commercial or license key notice, and these files do:");

    foreach (var file in notPublishable)
    {
        Console.Error.WriteLine($"  {file.Path}");
    }

    Console.Error.WriteLine(
        "Move the commercial functionality into a MeisterDev.ProPR project, or remove the notice if the file "
        + "does not implement any.");

    return 1;
}

return 0;

static string FindRepoRoot(string startDirectory)
{
    var current = new DirectoryInfo(startDirectory);

    while (current is not null)
    {
        // A checkout has a .git directory; a worktree has a .git file pointing at the shared git dir.
        var gitMarker = Path.Combine(current.FullName, ".git");
        if (Directory.Exists(gitMarker) || File.Exists(gitMarker))
        {
            return current.FullName;
        }

        current = current.Parent;
    }

    throw new InvalidOperationException("Could not locate repository root from script location.");
}

static string GetAppFilePath()
{
    foreach (var key in new[] { "EntryPointFilePath", "ScriptPath", "FilePath" })
    {
        if (AppContext.GetData(key) is string path && !string.IsNullOrWhiteSpace(path))
        {
            return Path.GetFullPath(path);
        }
    }

    if (Environment.GetCommandLineArgs() is { Length: > 0 } args)
    {
        var candidate = args[0];
        if (!string.IsNullOrWhiteSpace(candidate) && File.Exists(candidate))
        {
            return Path.GetFullPath(candidate);
        }
    }

    throw new InvalidOperationException("Could not determine the file-based app path.");
}
