#!/usr/bin/env -S dotnet --

using System.Text;

var appFilePath = GetAppFilePath();
var repoRoot = FindRepoRoot(Path.GetDirectoryName(appFilePath)!);
var outputFile = Path.Combine(repoRoot, "docs", "source-license-map.md");

const string commercialNotice = "This file implements commercial-only functionality. A commercial license is required to activate or use that functionality.";

var scanRoots = new[]
{
    Path.Combine(repoRoot, "src"),
    Path.Combine(repoRoot, "admin-ui", "src"),
};

var allowedExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    ".cs",
    ".ts",
    ".vue",
};

var commercialFiles = scanRoots
    .Where(Directory.Exists)
    .SelectMany(root => Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
    .Where(path => allowedExtensions.Contains(Path.GetExtension(path)))
    .Where(path => File.ReadAllText(path).Contains(commercialNotice, StringComparison.Ordinal))
    .Select(path => Path.GetRelativePath(repoRoot, path).Replace(Path.DirectorySeparatorChar, '/'))
    .OrderBy(path => path, StringComparer.Ordinal)
    .ToArray();

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

var builder = new StringBuilder();
builder.AppendLine("# Source License Map");
builder.AppendLine();
builder.AppendLine("This file is generated by `scripts/update-source-license-map.cs`.");
builder.AppendLine("Do not edit it manually.");
builder.AppendLine();
builder.AppendLine("| Path or file | Source license | Capability classification | Notes |");
builder.AppendLine("|---|---|---|---|");
builder.AppendLine("| `docs/` | Elastic License 2.0 unless otherwise noted | Documentation | This row is maintained by the generator as a repository convention. |");

foreach (var file in commercialFiles)
{
    var classification = "Commercial capability implementation";
    var notes = "Marked in-source with the commercial-only functionality notice.";

    if (file is "src/MeisterProPR.Api/Features/IdentityAndAccess/Controllers/TenantAuthController.cs"
        or "src/MeisterProPR.Infrastructure/Features/IdentityAndAccess/Persistence/TenantAuthService.cs")
    {
        classification = "Mixed file with commercial capability implementation";
        notes = "Marked in-source and contains shared behavior alongside commercial-only functionality.";
    }

    builder.Append("| `")
        .Append(file)
        .Append("` | Elastic License 2.0 | ")
        .Append(classification)
        .Append(" | ")
        .Append(notes)
        .AppendLine(" |");
}

builder.AppendLine("| All other repository files unless otherwise noted | Elastic License 2.0 | Community or shared | No commercial-only functionality notice detected in the scanned source files. |");

File.WriteAllText(outputFile, builder.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Updated {outputFile}");

static string FindRepoRoot(string startDirectory)
{
    var current = new DirectoryInfo(startDirectory);

    while (current is not null)
    {
        if (Directory.Exists(Path.Combine(current.FullName, ".git")))
        {
            return current.FullName;
        }

        current = current.Parent;
    }

    throw new InvalidOperationException("Could not locate repository root from script location.");
}

static string GetAppFilePath()
{
    foreach (var key in new[] { "EntryPointFilePath", "ScriptPath", "FilePath" })
    {
        if (AppContext.GetData(key) is string path && !string.IsNullOrWhiteSpace(path))
        {
            return Path.GetFullPath(path);
        }
    }

    if (Environment.GetCommandLineArgs() is { Length: > 0 } args)
    {
        var candidate = args[0];
        if (!string.IsNullOrWhiteSpace(candidate) && File.Exists(candidate))
        {
            return Path.GetFullPath(candidate);
        }
    }

    throw new InvalidOperationException("Could not determine the file-based app path.");
}
