// Copyright (c) Andreas Rain.
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license terms.

namespace MeisterProPR.Application.Features.Reviewing.Execution.Models;

public enum ReviewPassKind
{
    Baseline,

    /// <summary>
    ///     A resample/lens pass generated by multi-pass union. Additional independent passes over the same
    ///     file whose findings are unioned with the baseline pass before deduplication.
    /// </summary>
    MultiPassUnion,
}

public enum FindingProvenanceKind
{
    BaselineOnly,
    ProRVOnly,
    Both,
}

/// <summary>
///     Stable origin metadata for a final candidate finding.
/// </summary>
public sealed record CandidateFindingProvenance
{
    /// <summary>
    ///     Origin kind used for findings derived from a per-file comment.
    /// </summary>
    public const string PerFileCommentOrigin = "per_file_comment";

    /// <summary>
    ///     Origin kind used for findings synthesized across the full review.
    /// </summary>
    public const string SynthesizedCrossCuttingOrigin = "synthesized_cross_cutting";

    /// <summary>
    ///     Origin kind used for findings produced by deeper file-scoped follow-up.
    /// </summary>
    public const string DeeperFollowUpOrigin = "deeper_follow_up";

    /// <summary>
    ///     Origin kind used for findings retained through repeated judgment.
    /// </summary>
    public const string RepeatedJudgmentOrigin = "repeated_judgment";

    /// <summary>
    ///     Initializes stable provenance metadata for a candidate finding.
    /// </summary>
    /// <param name="originKind">Kind of source that produced the finding.</param>
    /// <param name="generatedByStage">Review stage that generated the finding.</param>
    /// <param name="sourceFilePath">Optional repository-relative source file path.</param>
    /// <param name="sourceFileResultId">Optional review file result identifier.</param>
    /// <param name="sourceCommentOrdinal">Optional ordinal of the originating comment within the file result.</param>
    /// <param name="evidenceSetId">Optional stable evidence-set identifier associated with the finding.</param>
    /// <param name="requiresExplicitSupport">Whether the finding requires explicit support before publication.</param>
    /// <param name="sourceOriginId">Optional stable identifier of the deeper follow-up task or repeated-judgment origin.</param>
    /// <param name="reviewPassKind">Review pass that produced the finding.</param>
    /// <param name="findingProvenanceKind">Normalized provenance classification for downstream handling.</param>
    /// <param name="unionPassIndex">
    ///     1-based index of the multi-pass union pass that produced the finding, or <see langword="null" /> when the
    ///     finding did not originate from a multi-pass union resample.
    /// </param>
    /// <param name="unionArmLabel">
    ///     Diversity-arm label of the multi-pass union pass that produced the finding (e.g. the resample arm), or
    ///     <see langword="null" /> when the finding did not originate from a multi-pass union resample.
    /// </param>
    /// <param name="unionLens">
    ///     Specialist lens of the multi-pass union pass that produced the finding (e.g. <c>security</c>), or
    ///     <see langword="null" /> for the baseline, ordinary resample passes, and non-union findings.
    /// </param>
    public CandidateFindingProvenance(
        string originKind,
        string generatedByStage,
        string? sourceFilePath = null,
        Guid? sourceFileResultId = null,
        int? sourceCommentOrdinal = null,
        string? evidenceSetId = null,
        bool requiresExplicitSupport = false,
        string? sourceOriginId = null,
        ReviewPassKind reviewPassKind = ReviewPassKind.Baseline,
        FindingProvenanceKind findingProvenanceKind = FindingProvenanceKind.BaselineOnly,
        int? unionPassIndex = null,
        string? unionArmLabel = null,
        string? unionLens = null)
    {
        if (string.IsNullOrWhiteSpace(originKind))
        {
            throw new ArgumentException("Origin kind is required.", nameof(originKind));
        }

        if (string.IsNullOrWhiteSpace(generatedByStage))
        {
            throw new ArgumentException("Generated-by stage is required.", nameof(generatedByStage));
        }

        this.OriginKind = originKind;
        this.GeneratedByStage = generatedByStage;
        this.SourceFilePath = sourceFilePath;
        this.SourceFileResultId = sourceFileResultId;
        this.SourceCommentOrdinal = sourceCommentOrdinal;
        this.EvidenceSetId = string.IsNullOrWhiteSpace(evidenceSetId) ? null : evidenceSetId;
        this.RequiresExplicitSupport = requiresExplicitSupport;
        this.SourceOriginId = string.IsNullOrWhiteSpace(sourceOriginId) ? null : sourceOriginId;
        this.ReviewPassKind = reviewPassKind;
        this.FindingProvenanceKind = findingProvenanceKind;
        this.UnionPassIndex = unionPassIndex;
        this.UnionArmLabel = string.IsNullOrWhiteSpace(unionArmLabel) ? null : unionArmLabel;
        this.UnionLens = string.IsNullOrWhiteSpace(unionLens) ? null : unionLens;
    }

    /// <summary>
    ///     Gets the kind of origin that produced the finding.
    /// </summary>
    public string OriginKind { get; }

    /// <summary>
    ///     Gets the review stage that generated the finding.
    /// </summary>
    public string GeneratedByStage { get; }

    /// <summary>
    ///     Gets the repository-relative source file path when the finding originated from a file result.
    /// </summary>
    public string? SourceFilePath { get; }

    /// <summary>
    ///     Gets the source file-result identifier when available.
    /// </summary>
    public Guid? SourceFileResultId { get; }

    /// <summary>
    ///     Gets the ordinal of the originating comment within the source file result when available.
    /// </summary>
    public int? SourceCommentOrdinal { get; }

    /// <summary>
    ///     Gets the stable evidence-set identifier used to evaluate this finding when available.
    /// </summary>
    public string? EvidenceSetId { get; }

    /// <summary>
    ///     Gets a value indicating whether this finding requires explicit support before publication.
    /// </summary>
    public bool RequiresExplicitSupport { get; }

    /// <summary>
    ///     Gets the stable origin identifier for deeper follow-up or repeated-judgment findings when available.
    /// </summary>
    public string? SourceOriginId { get; }

    /// <summary>
    ///     Gets the review pass that produced the current candidate instance.
    /// </summary>
    public ReviewPassKind ReviewPassKind { get; }

    /// <summary>
    ///     Gets the merged provenance classification for the current candidate instance.
    /// </summary>
    public FindingProvenanceKind FindingProvenanceKind { get; }

    /// <summary>
    ///     Gets the 1-based multi-pass union pass index that produced the finding, or <see langword="null" />
    ///     when the finding did not originate from a multi-pass union resample.
    /// </summary>
    public int? UnionPassIndex { get; }

    /// <summary>
    ///     Gets the multi-pass union diversity-arm label that produced the finding, or <see langword="null" />
    ///     when the finding did not originate from a multi-pass union resample.
    /// </summary>
    public string? UnionArmLabel { get; }

    /// <summary>
    ///     Gets the specialist lens of the multi-pass union pass that produced the finding (e.g. <c>security</c>),
    ///     or <see langword="null" /> for the baseline, ordinary resample passes, and non-union findings.
    /// </summary>
    public string? UnionLens { get; }

    /// <summary>
    ///     Resolves the single producing review pass for a published finding as a <see cref="ReviewPassKind" />
    ///     name, or <see langword="null" /> when no single pass owns it. Uses <see cref="FindingProvenanceKind" />
    ///     (the reliable classification) rather than the raw <see cref="ReviewPassKind" />, whose enum default
    ///     (<see cref="ReviewPassKind.Baseline" />) would otherwise mislabel synthesized cross-cutting findings
    ///     and merged (both-pass) findings as baseline. Returns null for synthesized cross-cutting findings and
    ///     for findings produced by both passes.
    /// </summary>
    public string? ResolveOriginPassKindName()
    {
        if (string.Equals(this.OriginKind, SynthesizedCrossCuttingOrigin, StringComparison.Ordinal))
        {
            return null;
        }

        // A multi-pass union resample owns the finding even after the merge classification collapses it to
        // BaselineOnly (a union-only finding merges as baseline). Surface the union pass so published/posted
        // findings render "Pass N" (via the carried UnionPassIndex) rather than the baseline label.
        if (this.ReviewPassKind == ReviewPassKind.MultiPassUnion)
        {
            return ReviewPassKind.MultiPassUnion.ToString();
        }

        return this.FindingProvenanceKind switch
        {
            FindingProvenanceKind.BaselineOnly => ReviewPassKind.Baseline.ToString(),
            _ => null,
        };
    }
}
